@IsTest
public class AccountTriggerHandlerTest {
    /*@isTest
    static void whenAccountCreatedThenEntitlementCreated() { TODO: UNCOMMENT
        System.assertEquals(0, [select count() from Entitlement]);

        Account account = new Account(Name = 'TestAcc');
        insert account; //entitlement will be added by trigger

        System.assertEquals(1, [select count() from Entitlement where AccountId = :account.Id]);
    }*/
}