public class Constants {
    public static final String STATUS_CLOSED_LOST = 'Closed Lost';
    public static final String STATUS_NOT_COMPLETED = 'Not Completed';
    public static final String STATUS_OBSOLETE = 'Obsolete';
    public static final String STAGENAME_CLOSED_LOST = 'Closed Lost';
    public static final String PROPERTY_QUALITY_BAD = 'Bad';
    public static final String ASSET_MANAGEMENT_CHATTER_GROUP_NAME = 'Asset Management Group';
    public static final String OPPORTUNITY_NOTIFICATION_GROUP_NAME = 'Opportunity Completion Group';
    public static final Double VAT_TAX = 1.2;
    public static final String INVENTORY_STATUS_RESERVED = 'Reserved';
    public static final String INVENTORY_STATUS_TERM_OUT = 'Terms Out';

}