public virtual class QuoteProductCodes {
//    TODO: move codes to one place
    public static final String OFFICE_RENT { get; set; }
    public static final String RETAIL_RENT { get; set; }
    public static final String LAB_SPACE { get; set; }
    public static final String CO_WORKING_DEDICATED_LICENCE_FEE { get; set; }
    public static final String CO_WORKING_HOT_DESK_LICENCE_FEE { get; set; }
    public static final String DEDICATED_DESK_SPACE { get; set; }
    public static final String ADDITIONAL_DESKS { get; set; }
    public static final String HALF_RENT { get; set; }
    public static final String RENT_FREE { get; set; }
    public static final String SERVICE_LICENCE_FEE { get; set; }
    public static final String DEPOSIT { get; set; }
    public static final String CUSTOMER_NOTICE { get; set; }
    public static final String STEPPED_RENT { get; set; }
    public static final String CAR_PARKING_LICENSE { get; set; }
    public static final String CAPEX_CONTRIBUTION { get; set; }
    public static final String CUSTOMER_BREAK_OPTION { get; set; }
    public static final String SUPPLIER_BREAK_OPTION { get; set; }
    static {
        OFFICE_RENT = 'OfficeRent';
        RETAIL_RENT = 'RetailRent';
        LAB_SPACE = 'LabSpace';
        CO_WORKING_DEDICATED_LICENCE_FEE = 'BSCW';
        CO_WORKING_HOT_DESK_LICENCE_FEE = 'BSDL';
        DEDICATED_DESK_SPACE = 'DedicatedDeskSpace';
        ADDITIONAL_DESKS = 'BSAS';
        HALF_RENT='HalfRent';
        RENT_FREE='RentFree';
        SERVICE_LICENCE_FEE = 'BSLF';
        DEPOSIT = 'BSDP';
        CUSTOMER_NOTICE = 'BSCB';
        STEPPED_RENT = 'SteppedRent';
        CAR_PARKING_LICENSE = 'CarParkLicense';
        CAPEX_CONTRIBUTION = 'CapexContribution';
        CUSTOMER_BREAK_OPTION = 'CustomerBreakOption';
        SUPPLIER_BREAK_OPTION = 'SupplierBreakOption';
    }
}